name: Publish Python distributions to PyPI and TestPyPI v2

on:
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-n-publish:
    name: Build and publish Python distribution
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Initialize Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies with pipenv
      run: |
        pip install pipenv
        pip install chardet
        pip install pipenv-setup
        pipenv install --deploy --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pipenv run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: pipenv run pytest --cov --cov-fail-under=80
    - name: Build binary wheel and a source tarball
      run: |
        pipenv-setup sync --dev
        python setup.py sdist
    #- name: Publish distribution to Test PyPI
    #  uses: pypa/gh-action-pypi-publish@master
    #  with:
    #    password: ${{ secrets.test_pypi_password }}
    #    repository_url: https://test.pypi.org/legacy/